language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    - TEST_DIR=/tmp/_pdvega/

before_install:
  - pip install pip --upgrade

install:
  - pip install -U -e .[dev]

script:
  - flake8 ./
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest --pyargs  --doctest-modules pdvega
